//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDCharaterDBApp
{
    using System;
    using System.Collections.Generic;

    public partial class CharaterSheet
    {
        public int SheetID { get; set; }
        public string CharaterName { get; set; }
        public int Description { get; set; }
        public string className { get; set; }
        public string result { get; set; }

    }
}
