//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDCharaterDBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.CharterSheets = new HashSet<CharterSheet>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int Armor { get; set; }
        public int Weapon1 { get; set; }
        public int Weapon2 { get; set; }
    
        public virtual Armor Armor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharterSheet> CharterSheets { get; set; }
        public virtual Weapon Weapon { get; set; }
        public virtual Weapon Weapon3 { get; set; }
    }
}
