//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDCharaterDBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        
        public int DescriptionID { get; set; }
        public string HairStyle { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public string SkinType { get; set; }
        public string SkinColor { get; set; }
        public string RaceName { get; set; }
        public string result { get; set; }
    }
}
