//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDCharaterDBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int StatsID { get; set; }
        public int StatsNum { get; set; }
        public Nullable<decimal> RacialBonus { get; set; }
        public decimal BaseScore { get; set; }
        public Nullable<decimal> Modifier { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual StatName StatName { get; set; }
    }
}
